service: serverless-typescript-example # Or serverless-practice
frameworkVersion: '3' 
provider:
  name: aws
  runtime: 
  region: us-east-1 
  memorySize: 256
  timeout: 30
  environment:
    NODE_ENV: ${opt:stage, 'dev'}


plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true
  patterns: 
    - '!test/**'
    - '!.git/**'
    - '!.github/**'

custom:
  esbuild:
    bundle: true
    minify: false 
    sourcemap: true
    exclude:
      - aws-sdk # Already available in Lambda
    target: node18 
    define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10

functions:
  hello: 
    handler: src/hello.handler 
    events:
      - httpApi: 
          path: /hello
          method: get
